import {
  Brain,
  FileText,
  MessageSquareText,
  PenTool,
  Sparkles,
  CalendarCheck,
} from "lucide-react";

const tools = [
  {
    icon: <FileText size={22} />,
    title: "AI Tute Generator",
    desc: "Generate structured notes, revision materials, and lesson tutes instantly.",
  },
  {
    icon: <Brain size={22} />,
    title: "AI MCQ Builder",
    desc: "Create exam-focused MCQs with answers and explanations.",
  },
  {
    icon: <Sparkles size={22} />,
    title: "AI Summary Engine",
    desc: "Turn long lessons into short, clear, student-friendly summaries.",
  },
  {
    icon: <PenTool size={22} />,
    title: "AI Poster Studio",
    desc: "Generate poster text, captions, hashtags, and campaign ideas.",
  },
  {
    icon: <CalendarCheck size={22} />,
    title: "AI Study Planner",
    desc: "Build personalized study schedules based on exam dates and weak areas.",
  },
  {
    icon: <MessageSquareText size={22} />,
    title: "AI Class Assistant",
    desc: "Support students with class FAQs, lesson guidance, and reminders.",
  },
];

function AIToolsHub() {
  return (
    <section className="aiToolsSection">
      <div className="sectionHeader">
        <span>AI TOOLS HUB</span>

        <h2>Content, Planning, and Automation — Generated by AI.</h2>

        <p>
          A powerful AI workspace designed to help teachers create content,
          support students, plan lessons, and manage digital education faster.
        </p>
      </div>

      <div className="aiToolsLayout">
        <div className="aiPromptPanel">
          <div className="promptTop">
            <div>
              <h3>AI Content Command</h3>
              <p>Generate learning materials in seconds.</p>
            </div>

            <div className="liveBadge">AI Active</div>
          </div>

          <div className="fakeInput">
            Generate 20 Advanced Level Biology MCQs for Cell Division with
            answers and explanations.
          </div>

          <div className="aiOutputBox">
            <div className="outputLine long"></div>
            <div className="outputLine medium"></div>
            <div className="outputLine short"></div>

            <div className="generatedCard">
              <h4>Generated Output Preview</h4>
              <p>
                01. During which phase of mitosis do chromosomes align at the
                equatorial plate?
              </p>
              <span>Answer: Metaphase · Difficulty: Medium</span>
            </div>

            <div className="generatedCard">
              <h4>AI Recommendation</h4>
              <p>
                Add a short diagram-based question to improve visual
                understanding.
              </p>
              <span>Suggested by NexNena AI Engine</span>
            </div>
          </div>
        </div>

        <div className="aiToolCards">
          {tools.map((tool) => (
            <div className="aiToolCard" key={tool.title}>
              <div className="aiToolIcon">{tool.icon}</div>
              <div>
                <h3>{tool.title}</h3>
                <p>{tool.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

export default AIToolsHub;